var readMore = document.getElementById('readMore');
var headline = document.getElementById('headline');
readMore.addEventListener('click', function(){

	headline.innerHTML='<p>”Men så en dag hände det som inte fick hända: jag träffade en svensk man. Han hette Patrik, och Patrik och jag förälskade oss i varandra. Till en början var jag livrädd för vad detta skulle innebära för mig och jag förklarade för honom vilka förutsättningar som måste gälla. Mina föräldrar fick inte under några som helst omständigheter veta något om oss</p>' +
	'<p>Trots riskerna valde vi att inleda ett förhållande, även om det innebar att vi endast kunde träffas inom fyra väggar och ständigt leva med skräcken att bli upptäckta. Efter ett års förhållande var vi trötta på att jämt träffas inomhus och smyga med vår kärlek och började bli alltmer oförsiktiga.</p>' +
	'<p>Vi började stegvis visa oss ute tillsammans på ställen där vi kunde vara någorlunda säkra på att inte träffa på någon i familjen eller släkten. En dag ledde vår oförsiktighet till att vi upptäcktes av min far, som självklart exploderade av ilska och började slå på mig och Patrik.</p>' +
	'<p>Hans reaktion var för mig fullt förståelig. Som far och familjeöverhuvud är det hans uppgift att vaka över familjens heder. Han ska värna om och skydda kvinnliga släktingars sexuella uppförande och se till att döttrarnas oskuld är bevarad fram till giftermålet. Om den nyblivne maken till hans döttrar får veta att hon inte är oskuld på bröllopsnatten kan han direkt kräva skilsmässa. Än i dag överlämnas det blodfläckade lakanet till brudens svärmor så att hon kan visa sin omgivning att de har fått en ärbar och ren kvinna. Eftersom familjen förstod att vi var ett par kunde de snabbt dra slutsatsen att jag inte längre hade kvar min oskuld”.</p>' +
	'<p>Citat ur Fadime Sahindals tal; från den första Riksdagskonferensen om våld i hederns namn; 2001-11-20. - En sammanfattning av hela konferensen finns på: <a href="http://www.humanrights.se/publikationer/" target="_blank">HumanRights.se</a></p>' +
	'<i class="fa fa-long-arrow-left" aria-hidden="true"></i> <a id="goBack">Gå tillbaka</a>';

	document.getElementById('goBack').addEventListener('click', function() {
		headline.innerHTML = '<h2>Några ord om diskriminering och våld i hederns namn</h2>' +
			'<p>Diskriminering, förtryck, hot och våld i hederns namn är vardag för miljoner ungdomar världen över. I vissa länder kan kyskhetsbrott straffas med döden. I Sverige lever idag uppskattningsvis över 100 000 ungdomar ett liv utan frihet att bestämma över sina eventuella kärleksrelationer (uppgift från regerings utredning, Carin Götblad, 2014).</p>' +
			'<p>Efter de uppmärksammade morden på Pela Atroshi (1999) och Fadime Sahindal (2002) har fenomenet förtryck och våld i hederns namn skapat en starkt känsloladdad samhällsdebatt i Sverige. De två unga kvinnorna och senare den nittonåriga pojken Abbas Rezai (2005) mördades av nära familjemedlemmar för att de ville leva sina egna liv och det ansågs vanhedra familjen. Ändå kategoriseras ofta våld i hederns namn missvisande som ”mäns våld mot kvinnor” och därigenom missar man släktens kollektiva diskriminering och våld mot ungdomar, i första hand döttrar. Det kan handla om förbud mot umgänge med det motsatta könet, förbud mot föräktenskapliga kärleksrelationer, strikta klädkoder, könssegregerad uppfostran, tvångsgiftermål och barnäktenskap. I högsta gard berörs även pojkar och unga män. Även homo- och bisexuella drabbas.</p>' +
			'<p>Ungdomarna i fråga antigen internaliserar eller underkastar sig släktens hedersnormer men i många fall försöker de leva ett dubbelt liv, i hemlighet. Att "tvätta bort skammen" för att återupprätta familjens heder kan också lösas genom att förskjuta eller tvångsgifta en dotter (t.ex.).</p>' +
			'<p>Hedersmord är bara toppen av ett isberg. FN och Amnesty uppger att det sker femtusen hedersmord i världen, årligen. Samtidigt vet man att de flesta hedersmord bokförs som olyckor eller självmord. "Köksolyckor", syra-kastning eller påtvingat självmord (balkongflickor) är olika former av våld i hederns namn.</p>' +
			'<p>Allt detta kunde förebyggas om våra makthavare skulle se till att de kulturspecifika kollektiva normerna som kommer i konflikt med individens mänskliga rättigheter förändrades. Men femton år efter mordet på Fadime medger fler beslutfattare att ”vi är fega” som låter som upprepningar av dåvarande integrationsministern Mona Sahlins berömda erkännande: ”jag har varit feg, vi har svikit invandrarflickorna” (den 8 juni 2001, DN).</p>';
	});

});